#Blender Screen Layout
#Scott Kevern
#November 2018

<CustButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1
    size: 200, 60
    background_normal: 'blender1.png'
    background_down: ''
    background_color: .88, .88, .88, 1
    size_hint: .4, .3

<CustomWidget>:
    CustButton:
        text: "Blend"
        pos: 300, 400
    
    CustButton:
        text: "Clean"
        pos: 300, 300
        
    CustButton:
        text: "Dispense"
        pos: 300, 200
        
        
